apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
  namespace 'expo.modules.healthsync'
  compileSdkVersion safeExtGet('compileSdkVersion', 36)

  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 26)
    targetSdkVersion safeExtGet('targetSdkVersion', 36)
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'androidx.health.connect:connect-client:1.1.0'
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
