/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fd39f50e6b071837f2baf9f790c9b376)
interface __BaseEnv_Env {
	DISCORD_STATE: KVNamespace;
	STAR_HISTORY: KVNamespace;
	MEAL_SHARES: KVNamespace;
	CHALLENGE_DB: D1Database;
	CHALLENGE_API_RATE_LIMITER: RateLimit;
	CHALLENGE_CREATE_RATE_LIMITER: RateLimit;
	MEAL_SHARE_CREATE_RATE_LIMITER: RateLimit;
	MEAL_SHARE_READ_RATE_LIMITER: RateLimit;
	HOSTED_AI_USER_RATE_LIMITER: RateLimit;
	HOSTED_AI_ADDRESS_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	DISCORD_PUBLIC_KEY: "0ce6e6014282b489ce0930fad550e978c7d623cc71040d14250223110a9a9f57";
	DISCORD_APPLICATION_ID: "1548469419922038845";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
