/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 17409eb4befb87297aedd0da438308ee)
interface __BaseEnv_Env {
	STAR_HISTORY: KVNamespace;
	MEAL_SHARES: KVNamespace;
	CHALLENGE_DB: D1Database;
	CHALLENGE_API_RATE_LIMITER: RateLimit;
	CHALLENGE_CREATE_RATE_LIMITER: RateLimit;
	MEAL_SHARE_CREATE_RATE_LIMITER: RateLimit;
	MEAL_SHARE_READ_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
